# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/bd_43c9.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9 || ORIG_REF_NAME==bd_43c9} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_0/bd_43c9_build_info_cmc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_build_info_cmc_0 || ORIG_REF_NAME==bd_43c9_build_info_cmc_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_1/bd_43c9_build_info_host_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_build_info_host_0 || ORIG_REF_NAME==bd_43c9_build_info_host_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_2/bd_43c9_axi_gpio_timebase_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_gpio_timebase_0 || ORIG_REF_NAME==bd_43c9_axi_gpio_timebase_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_3/bd_43c9_axi_gpio_cmc_mb_rst_n_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_gpio_cmc_mb_rst_n_0 || ORIG_REF_NAME==bd_43c9_axi_gpio_cmc_mb_rst_n_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_4/bd_43c9_axi_gpio_hbm_temp_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_gpio_hbm_temp_0 || ORIG_REF_NAME==bd_43c9_axi_gpio_hbm_temp_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_5/bd_43c9_axi_gpio_cms_features_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_gpio_cms_features_0 || ORIG_REF_NAME==bd_43c9_axi_gpio_cms_features_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_6/bd_43c9_cms_feature_concat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_cms_feature_concat_0 || ORIG_REF_NAME==bd_43c9_cms_feature_concat_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_7/bd_43c9_HBM_Temp_Sensor_Enable_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_HBM_Temp_Sensor_Enable_0 || ORIG_REF_NAME==bd_43c9_HBM_Temp_Sensor_Enable_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_8/bd_43c9_QSFP_Write_Enable_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_QSFP_Write_Enable_0 || ORIG_REF_NAME==bd_43c9_QSFP_Write_Enable_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_9/bd_43c9_VCCInt_Scaling_Enable_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_VCCInt_Scaling_Enable_0 || ORIG_REF_NAME==bd_43c9_VCCInt_Scaling_Enable_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_10/bd_43c9_Reserved_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_Reserved_3_0 || ORIG_REF_NAME==bd_43c9_Reserved_3_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_11/bd_43c9_Reserved_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_Reserved_4_0 || ORIG_REF_NAME==bd_43c9_Reserved_4_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_12/bd_43c9_Reserved_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_Reserved_5_0 || ORIG_REF_NAME==bd_43c9_Reserved_5_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_13/bd_43c9_Reserved_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_Reserved_6_0 || ORIG_REF_NAME==bd_43c9_Reserved_6_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_14/bd_43c9_Reserved_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_Reserved_7_0 || ORIG_REF_NAME==bd_43c9_Reserved_7_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_15/bd_43c9_axi_gpio_wdt_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_gpio_wdt_0 || ORIG_REF_NAME==bd_43c9_axi_gpio_wdt_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_16/bd_43c9_axi_gpio_mb_intr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_gpio_mb_intr_0 || ORIG_REF_NAME==bd_43c9_axi_gpio_mb_intr_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_17/bd_43c9_axi_gpio_mutex_cmc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_gpio_mutex_cmc_0 || ORIG_REF_NAME==bd_43c9_axi_gpio_mutex_cmc_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_18/bd_43c9_axi_gpio_mutex_host_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_gpio_mutex_host_0 || ORIG_REF_NAME==bd_43c9_axi_gpio_mutex_host_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_19/bd_43c9_axi_intc_cmc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_intc_cmc_0 || ORIG_REF_NAME==bd_43c9_axi_intc_cmc_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_20/bd_43c9_axi_intc_host_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_intc_host_0 || ORIG_REF_NAME==bd_43c9_axi_intc_host_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_21/bd_43c9_axi_timebase_wdt_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_timebase_wdt_0 || ORIG_REF_NAME==bd_43c9_axi_timebase_wdt_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_22/bd_43c9_axi_uartlite_satellite_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_uartlite_satellite_0 || ORIG_REF_NAME==bd_43c9_axi_uartlite_satellite_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_23/bd_43c9_axi_uartlite_usb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_uartlite_usb_0 || ORIG_REF_NAME==bd_43c9_axi_uartlite_usb_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_25/bd_43c9_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_xbar_0 || ORIG_REF_NAME==bd_43c9_xbar_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_24/bd_43c9_axi_ic_cmc_local_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_ic_cmc_local_0 || ORIG_REF_NAME==bd_43c9_axi_ic_cmc_local_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_27/bd_43c9_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_xbar_1 || ORIG_REF_NAME==bd_43c9_xbar_1} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_26/bd_43c9_axi_ic_mgmt_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_ic_mgmt_0 || ORIG_REF_NAME==bd_43c9_axi_ic_mgmt_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_28/bd_43c9_axi_bram_ctrl_firmware_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_bram_ctrl_firmware_0 || ORIG_REF_NAME==bd_43c9_axi_bram_ctrl_firmware_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_29/bd_43c9_dlmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_dlmb_0 || ORIG_REF_NAME==bd_43c9_dlmb_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_30/bd_43c9_ilmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_ilmb_0 || ORIG_REF_NAME==bd_43c9_ilmb_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_31/bd_43c9_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_lmb_bram_0 || ORIG_REF_NAME==bd_43c9_lmb_bram_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_32/bd_43c9_lmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_lmb_bram_if_cntlr_0 || ORIG_REF_NAME==bd_43c9_lmb_bram_if_cntlr_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_33/bd_43c9_microblaze_cmc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_microblaze_cmc_0 || ORIG_REF_NAME==bd_43c9_microblaze_cmc_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_34/bd_43c9_microblaze_axi_vip_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_microblaze_axi_vip_0 || ORIG_REF_NAME==bd_43c9_microblaze_axi_vip_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_35/bd_43c9_reachout_axi_vip_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_reachout_axi_vip_0 || ORIG_REF_NAME==bd_43c9_reachout_axi_vip_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_36/bd_43c9_msp432_bsl_crc_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_msp432_bsl_crc_gen_0 || ORIG_REF_NAME==bd_43c9_msp432_bsl_crc_gen_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_37/bd_43c9_psreset_cmc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_psreset_cmc_0 || ORIG_REF_NAME==bd_43c9_psreset_cmc_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_38/bd_43c9_reg_map_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_reg_map_bram_0 || ORIG_REF_NAME==bd_43c9_reg_map_bram_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_39/bd_43c9_axi_bram_ctrl_regmap_cmc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_bram_ctrl_regmap_cmc_0 || ORIG_REF_NAME==bd_43c9_axi_bram_ctrl_regmap_cmc_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_40/bd_43c9_axi_bram_ctrl_regmap_host_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_bram_ctrl_regmap_host_0 || ORIG_REF_NAME==bd_43c9_axi_bram_ctrl_regmap_host_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_41/bd_43c9_concat_intr_cmc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_concat_intr_cmc_0 || ORIG_REF_NAME==bd_43c9_concat_intr_cmc_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_42/bd_43c9_concat_hbm_temp_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_concat_hbm_temp_0 || ORIG_REF_NAME==bd_43c9_concat_hbm_temp_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_43/bd_43c9_concat_host_interrupts_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_concat_host_interrupts_0 || ORIG_REF_NAME==bd_43c9_concat_host_interrupts_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_44/bd_43c9_gnd_bus_1_hbm_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_gnd_bus_1_hbm_0 || ORIG_REF_NAME==bd_43c9_gnd_bus_1_hbm_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_45/bd_43c9_gnd_bus_1_interrupts_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_gnd_bus_1_interrupts_0 || ORIG_REF_NAME==bd_43c9_gnd_bus_1_interrupts_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_46/bd_43c9_freerun_counter_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_freerun_counter_0 || ORIG_REF_NAME==bd_43c9_freerun_counter_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_47/bd_43c9_axi_gpio_qsfp_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_gpio_qsfp_0 || ORIG_REF_NAME==bd_43c9_axi_gpio_qsfp_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_48/bd_43c9_concat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_concat_1_0 || ORIG_REF_NAME==bd_43c9_concat_1_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_49/bd_43c9_concat_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_concat_2_0 || ORIG_REF_NAME==bd_43c9_concat_2_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_50/bd_43c9_gnd_bus_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_gnd_bus_1_0 || ORIG_REF_NAME==bd_43c9_gnd_bus_1_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_51/bd_43c9_slice_gpio1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_slice_gpio1_0_0 || ORIG_REF_NAME==bd_43c9_slice_gpio1_0_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_52/bd_43c9_slice_gpio1_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_slice_gpio1_1_0 || ORIG_REF_NAME==bd_43c9_slice_gpio1_1_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_53/bd_43c9_slice_gpio1_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_slice_gpio1_2_0 || ORIG_REF_NAME==bd_43c9_slice_gpio1_2_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_54/bd_43c9_slice_gpio2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_slice_gpio2_0_0 || ORIG_REF_NAME==bd_43c9_slice_gpio2_0_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_55/bd_43c9_slice_gpio2_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_slice_gpio2_1_0 || ORIG_REF_NAME==bd_43c9_slice_gpio2_1_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_56/bd_43c9_slice_gpio2_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_slice_gpio2_2_0 || ORIG_REF_NAME==bd_43c9_slice_gpio2_2_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_57/bd_43c9_and_gate_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_and_gate_0 || ORIG_REF_NAME==bd_43c9_and_gate_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_58/bd_43c9_reset_inverter_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_reset_inverter_0 || ORIG_REF_NAME==bd_43c9_reset_inverter_0} -quiet] -quiet

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/bd_43c9_ooc.xdc

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_0/synth/bd_fb99_shell_cmc_subsystem_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_fb99_shell_cmc_subsystem_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# Block Designs: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/bd_43c9.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9 || ORIG_REF_NAME==bd_43c9} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_0/bd_43c9_build_info_cmc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_build_info_cmc_0 || ORIG_REF_NAME==bd_43c9_build_info_cmc_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_1/bd_43c9_build_info_host_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_build_info_host_0 || ORIG_REF_NAME==bd_43c9_build_info_host_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_2/bd_43c9_axi_gpio_timebase_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_gpio_timebase_0 || ORIG_REF_NAME==bd_43c9_axi_gpio_timebase_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_3/bd_43c9_axi_gpio_cmc_mb_rst_n_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_gpio_cmc_mb_rst_n_0 || ORIG_REF_NAME==bd_43c9_axi_gpio_cmc_mb_rst_n_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_4/bd_43c9_axi_gpio_hbm_temp_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_gpio_hbm_temp_0 || ORIG_REF_NAME==bd_43c9_axi_gpio_hbm_temp_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_5/bd_43c9_axi_gpio_cms_features_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_gpio_cms_features_0 || ORIG_REF_NAME==bd_43c9_axi_gpio_cms_features_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_6/bd_43c9_cms_feature_concat_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_cms_feature_concat_0 || ORIG_REF_NAME==bd_43c9_cms_feature_concat_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_7/bd_43c9_HBM_Temp_Sensor_Enable_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_HBM_Temp_Sensor_Enable_0 || ORIG_REF_NAME==bd_43c9_HBM_Temp_Sensor_Enable_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_8/bd_43c9_QSFP_Write_Enable_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_QSFP_Write_Enable_0 || ORIG_REF_NAME==bd_43c9_QSFP_Write_Enable_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_9/bd_43c9_VCCInt_Scaling_Enable_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_VCCInt_Scaling_Enable_0 || ORIG_REF_NAME==bd_43c9_VCCInt_Scaling_Enable_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_10/bd_43c9_Reserved_3_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_Reserved_3_0 || ORIG_REF_NAME==bd_43c9_Reserved_3_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_11/bd_43c9_Reserved_4_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_Reserved_4_0 || ORIG_REF_NAME==bd_43c9_Reserved_4_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_12/bd_43c9_Reserved_5_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_Reserved_5_0 || ORIG_REF_NAME==bd_43c9_Reserved_5_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_13/bd_43c9_Reserved_6_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_Reserved_6_0 || ORIG_REF_NAME==bd_43c9_Reserved_6_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_14/bd_43c9_Reserved_7_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_Reserved_7_0 || ORIG_REF_NAME==bd_43c9_Reserved_7_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_15/bd_43c9_axi_gpio_wdt_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_gpio_wdt_0 || ORIG_REF_NAME==bd_43c9_axi_gpio_wdt_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_16/bd_43c9_axi_gpio_mb_intr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_gpio_mb_intr_0 || ORIG_REF_NAME==bd_43c9_axi_gpio_mb_intr_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_17/bd_43c9_axi_gpio_mutex_cmc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_gpio_mutex_cmc_0 || ORIG_REF_NAME==bd_43c9_axi_gpio_mutex_cmc_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_18/bd_43c9_axi_gpio_mutex_host_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_gpio_mutex_host_0 || ORIG_REF_NAME==bd_43c9_axi_gpio_mutex_host_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_19/bd_43c9_axi_intc_cmc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_intc_cmc_0 || ORIG_REF_NAME==bd_43c9_axi_intc_cmc_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_20/bd_43c9_axi_intc_host_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_intc_host_0 || ORIG_REF_NAME==bd_43c9_axi_intc_host_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_21/bd_43c9_axi_timebase_wdt_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_timebase_wdt_0 || ORIG_REF_NAME==bd_43c9_axi_timebase_wdt_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_22/bd_43c9_axi_uartlite_satellite_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_uartlite_satellite_0 || ORIG_REF_NAME==bd_43c9_axi_uartlite_satellite_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_23/bd_43c9_axi_uartlite_usb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_uartlite_usb_0 || ORIG_REF_NAME==bd_43c9_axi_uartlite_usb_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_25/bd_43c9_xbar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_xbar_0 || ORIG_REF_NAME==bd_43c9_xbar_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_24/bd_43c9_axi_ic_cmc_local_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_ic_cmc_local_0 || ORIG_REF_NAME==bd_43c9_axi_ic_cmc_local_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_27/bd_43c9_xbar_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_xbar_1 || ORIG_REF_NAME==bd_43c9_xbar_1} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_26/bd_43c9_axi_ic_mgmt_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_ic_mgmt_0 || ORIG_REF_NAME==bd_43c9_axi_ic_mgmt_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_28/bd_43c9_axi_bram_ctrl_firmware_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_bram_ctrl_firmware_0 || ORIG_REF_NAME==bd_43c9_axi_bram_ctrl_firmware_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_29/bd_43c9_dlmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_dlmb_0 || ORIG_REF_NAME==bd_43c9_dlmb_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_30/bd_43c9_ilmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_ilmb_0 || ORIG_REF_NAME==bd_43c9_ilmb_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_31/bd_43c9_lmb_bram_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_lmb_bram_0 || ORIG_REF_NAME==bd_43c9_lmb_bram_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_32/bd_43c9_lmb_bram_if_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_lmb_bram_if_cntlr_0 || ORIG_REF_NAME==bd_43c9_lmb_bram_if_cntlr_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_33/bd_43c9_microblaze_cmc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_microblaze_cmc_0 || ORIG_REF_NAME==bd_43c9_microblaze_cmc_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_34/bd_43c9_microblaze_axi_vip_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_microblaze_axi_vip_0 || ORIG_REF_NAME==bd_43c9_microblaze_axi_vip_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_35/bd_43c9_reachout_axi_vip_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_reachout_axi_vip_0 || ORIG_REF_NAME==bd_43c9_reachout_axi_vip_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_36/bd_43c9_msp432_bsl_crc_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_msp432_bsl_crc_gen_0 || ORIG_REF_NAME==bd_43c9_msp432_bsl_crc_gen_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_37/bd_43c9_psreset_cmc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_psreset_cmc_0 || ORIG_REF_NAME==bd_43c9_psreset_cmc_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_38/bd_43c9_reg_map_bram_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_reg_map_bram_0 || ORIG_REF_NAME==bd_43c9_reg_map_bram_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_39/bd_43c9_axi_bram_ctrl_regmap_cmc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_bram_ctrl_regmap_cmc_0 || ORIG_REF_NAME==bd_43c9_axi_bram_ctrl_regmap_cmc_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_40/bd_43c9_axi_bram_ctrl_regmap_host_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_bram_ctrl_regmap_host_0 || ORIG_REF_NAME==bd_43c9_axi_bram_ctrl_regmap_host_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_41/bd_43c9_concat_intr_cmc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_concat_intr_cmc_0 || ORIG_REF_NAME==bd_43c9_concat_intr_cmc_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_42/bd_43c9_concat_hbm_temp_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_concat_hbm_temp_0 || ORIG_REF_NAME==bd_43c9_concat_hbm_temp_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_43/bd_43c9_concat_host_interrupts_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_concat_host_interrupts_0 || ORIG_REF_NAME==bd_43c9_concat_host_interrupts_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_44/bd_43c9_gnd_bus_1_hbm_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_gnd_bus_1_hbm_0 || ORIG_REF_NAME==bd_43c9_gnd_bus_1_hbm_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_45/bd_43c9_gnd_bus_1_interrupts_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_gnd_bus_1_interrupts_0 || ORIG_REF_NAME==bd_43c9_gnd_bus_1_interrupts_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_46/bd_43c9_freerun_counter_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_freerun_counter_0 || ORIG_REF_NAME==bd_43c9_freerun_counter_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_47/bd_43c9_axi_gpio_qsfp_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_axi_gpio_qsfp_0 || ORIG_REF_NAME==bd_43c9_axi_gpio_qsfp_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_48/bd_43c9_concat_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_concat_1_0 || ORIG_REF_NAME==bd_43c9_concat_1_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_49/bd_43c9_concat_2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_concat_2_0 || ORIG_REF_NAME==bd_43c9_concat_2_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_50/bd_43c9_gnd_bus_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_gnd_bus_1_0 || ORIG_REF_NAME==bd_43c9_gnd_bus_1_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_51/bd_43c9_slice_gpio1_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_slice_gpio1_0_0 || ORIG_REF_NAME==bd_43c9_slice_gpio1_0_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_52/bd_43c9_slice_gpio1_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_slice_gpio1_1_0 || ORIG_REF_NAME==bd_43c9_slice_gpio1_1_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_53/bd_43c9_slice_gpio1_2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_slice_gpio1_2_0 || ORIG_REF_NAME==bd_43c9_slice_gpio1_2_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_54/bd_43c9_slice_gpio2_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_slice_gpio2_0_0 || ORIG_REF_NAME==bd_43c9_slice_gpio2_0_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_55/bd_43c9_slice_gpio2_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_slice_gpio2_1_0 || ORIG_REF_NAME==bd_43c9_slice_gpio2_1_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_56/bd_43c9_slice_gpio2_2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_slice_gpio2_2_0 || ORIG_REF_NAME==bd_43c9_slice_gpio2_2_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_57/bd_43c9_and_gate_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_and_gate_0 || ORIG_REF_NAME==bd_43c9_and_gate_0} -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_58/bd_43c9_reset_inverter_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_43c9_reset_inverter_0 || ORIG_REF_NAME==bd_43c9_reset_inverter_0} -quiet] -quiet

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/bd_43c9_ooc.xdc

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_0/synth/bd_fb99_shell_cmc_subsystem_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_fb99_shell_cmc_subsystem_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
