# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga.xdc

# XDC: /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/placement.xdc

# XDC: /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/cfgmclk.xdc

# XDC: /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/boot.xdc

# TCL: /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axi/syn/vivado/axil_cdc.tcl

# TCL: /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axis/syn/vivado/axis_async_fifo.tcl

# TCL: /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axis/syn/vivado/sync_reset.tcl

# TCL: /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/eth/syn/vivado/ptp_clock_cdc.tcl

# TCL: /home/ubuntu/git_repos/corundum/fpga/common/syn/vivado/mqnic_port.tcl

# TCL: /home/ubuntu/git_repos/corundum/fpga/common/syn/vivado/mqnic_ptp_clock.tcl

# TCL: /home/ubuntu/git_repos/corundum/fpga/common/syn/vivado/mqnic_rb_clk_info.tcl

# TCL: /home/ubuntu/git_repos/corundum/fpga/common/syn/vivado/rb_drp.tcl

# TCL: /home/ubuntu/git_repos/corundum/fpga/common/syn/vivado/cmac_gty_wrapper.tcl

# TCL: /home/ubuntu/git_repos/corundum/fpga/common/syn/vivado/cmac_gty_ch_wrapper.tcl

# IP: ip/cmac_usplus/cmac_usplus.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cmac_usplus || ORIG_REF_NAME==cmac_usplus} -quiet] -quiet

# Block Designs: bd/cms/cms.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cms || ORIG_REF_NAME==cms} -quiet] -quiet

# IP: bd/cms/ip/cms_cms_subsystem_0_0/cms_cms_subsystem_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cms_cms_subsystem_0_0 || ORIG_REF_NAME==cms_cms_subsystem_0_0} -quiet] -quiet

# XDC: /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/cmac_usplus/synth/cmac_usplus_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cmac_usplus || ORIG_REF_NAME==cmac_usplus} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/cmac_usplus/synth/cmac_usplus_ooc.xdc

# XDC: /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/cms_ooc.xdc
