# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.runs/synth_1/fpga.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcu250-figd2104-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.cache/wt [current_project]
set_property parent.project_path /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property generic {FPGA_ID=32'h04b57093 FW_ID=32'h00000000 FW_VER=32'h00000100 BOARD_ID=32'h10ee90fa BOARD_VER=32'h01000000 BUILD_DATE=32'd1689164279 GIT_HASH=32'h56c89640 RELEASE_INFO=32'h00000000 IF_COUNT=2 PORTS_PER_IF=1 SCHED_PER_IF=1 PORT_MASK=0 CLK_PERIOD_NS_NUM=4 CLK_PERIOD_NS_DENOM=1 PTP_CLOCK_PIPELINE=0 PTP_CLOCK_CDC_PIPELINE=0 PTP_PORT_CDC_PIPELINE=0 PTP_PEROUT_ENABLE=0 PTP_PEROUT_COUNT=1 EVENT_QUEUE_OP_TABLE_SIZE=32 TX_QUEUE_OP_TABLE_SIZE=32 RX_QUEUE_OP_TABLE_SIZE=32 TX_CPL_QUEUE_OP_TABLE_SIZE=32 RX_CPL_QUEUE_OP_TABLE_SIZE=32 EVENT_QUEUE_INDEX_WIDTH=6 TX_QUEUE_INDEX_WIDTH=13 RX_QUEUE_INDEX_WIDTH=8 TX_CPL_QUEUE_INDEX_WIDTH=13 RX_CPL_QUEUE_INDEX_WIDTH=8 EVENT_QUEUE_PIPELINE=3 TX_QUEUE_PIPELINE=4 RX_QUEUE_PIPELINE=3 TX_CPL_QUEUE_PIPELINE=4 RX_CPL_QUEUE_PIPELINE=3 TX_DESC_TABLE_SIZE=32 RX_DESC_TABLE_SIZE=32 RX_INDIR_TBL_ADDR_WIDTH=8 TX_SCHEDULER_OP_TABLE_SIZE=32 TX_SCHEDULER_PIPELINE=4 TDMA_INDEX_WIDTH=6 PTP_TS_ENABLE=1 TX_CPL_FIFO_DEPTH=32 TX_CHECKSUM_ENABLE=1 RX_HASH_ENABLE=1 RX_CHECKSUM_ENABLE=1 TX_FIFO_DEPTH=32768 RX_FIFO_DEPTH=131072 MAX_TX_SIZE=9214 MAX_RX_SIZE=9214 TX_RAM_SIZE=131072 RX_RAM_SIZE=131072 DDR_CH=4 DDR_ENABLE=0 AXI_DDR_ID_WIDTH=8 AXI_DDR_MAX_BURST_LEN=256 APP_ID=32'h00000000 APP_ENABLE=0 APP_CTRL_ENABLE=1 APP_DMA_ENABLE=1 APP_AXIS_DIRECT_ENABLE=1 APP_AXIS_SYNC_ENABLE=1 APP_AXIS_IF_ENABLE=1 APP_STAT_ENABLE=1 DMA_IMM_ENABLE=0 DMA_IMM_WIDTH=32 DMA_LEN_WIDTH=16 DMA_TAG_WIDTH=16 RAM_ADDR_WIDTH=17 RAM_PIPELINE=2 IRQ_INDEX_WIDTH=6 AXIL_CTRL_DATA_WIDTH=32 AXIL_CTRL_ADDR_WIDTH=24 AXIL_APP_CTRL_DATA_WIDTH=32 AXIL_APP_CTRL_ADDR_WIDTH=24 AXIS_ETH_TX_PIPELINE=4 AXIS_ETH_TX_FIFO_PIPELINE=4 AXIS_ETH_TX_TS_PIPELINE=4 AXIS_ETH_RX_PIPELINE=4 AXIS_ETH_RX_FIFO_PIPELINE=4 STAT_ENABLE=1 STAT_DMA_ENABLE=1 STAT_PCIE_ENABLE=1 STAT_INC_WIDTH=24 STAT_ID_WIDTH=12 AXIS_PCIE_DATA_WIDTH=512} [current_fileset]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axi/rtl/arbiter.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axi/rtl/axil_cdc.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axi/rtl/axil_cdc_rd.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axi/rtl/axil_cdc_wr.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axi/rtl/axil_crossbar.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axi/rtl/axil_crossbar_addr.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axi/rtl/axil_crossbar_rd.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axi/rtl/axil_crossbar_wr.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axi/rtl/axil_reg_if.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axi/rtl/axil_reg_if_rd.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axi/rtl/axil_reg_if_wr.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axi/rtl/axil_register_rd.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axi/rtl/axil_register_wr.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axis/rtl/axis_adapter.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axis/rtl/axis_arb_mux.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axis/rtl/axis_async_fifo.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axis/rtl/axis_async_fifo_adapter.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axis/rtl/axis_demux.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axis/rtl/axis_fifo.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axis/rtl/axis_fifo_adapter.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axis/rtl/axis_pipeline_fifo.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/cmac_gty_ch_wrapper.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/cmac_gty_wrapper.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/cmac_pad.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/hdl/cms_wrapper.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/cpl_op_mux.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/cpl_queue_manager.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/cpl_write.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/debounce_switch.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/desc_fetch.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/desc_op_mux.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/dma_client_axis_sink.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/dma_client_axis_source.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/dma_if_desc_mux.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/dma_if_mux.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/dma_if_mux_rd.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/dma_if_mux_wr.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/dma_if_pcie.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/dma_if_pcie_rd.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/dma_if_pcie_wr.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/dma_psdpram.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/dma_ram_demux_rd.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/dma_ram_demux_wr.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/event_mux.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/fpga_core.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/irq_rate_limit.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/mac_ts_insert.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/mqnic_core.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/mqnic_core_pcie.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/mqnic_core_pcie_us.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/mqnic_dram_if.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/mqnic_egress.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/mqnic_ingress.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/mqnic_interface.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/mqnic_interface_rx.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/mqnic_interface_tx.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/mqnic_l2_egress.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/mqnic_l2_ingress.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/mqnic_port.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/mqnic_port_map_mac_axis.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/mqnic_port_rx.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/mqnic_port_tx.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/mqnic_ptp.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/mqnic_ptp_clock.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/mqnic_ptp_perout.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/mqnic_rb_clk_info.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/mqnic_rx_queue_map.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/mqnic_tx_scheduler_block_rr.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/pcie_axil_master.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/pcie_msix.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/pcie_tlp_demux.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/pcie_tlp_demux_bar.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/pcie_tlp_fifo.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/pcie_tlp_fifo_raw.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/pcie_tlp_mux.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/pcie_us_cfg.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/pcie_us_if.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/pcie_us_if_cc.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/pcie_us_if_cq.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/pcie_us_if_rc.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/pcie_us_if_rq.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axi/rtl/priority_encoder.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/eth/rtl/ptp_clock.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/eth/rtl/ptp_clock_cdc.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/eth/rtl/ptp_perout.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/pcie/rtl/pulse_merge.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/queue_manager.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/rb_drp.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/rx_checksum.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/rx_engine.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/rx_fifo.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/rx_hash.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/stats_collect.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/stats_counter.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/stats_dma_if_pcie.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/stats_dma_latency.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/stats_pcie_if.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/stats_pcie_tlp.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axis/rtl/sync_reset.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/sync_signal.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/tx_checksum.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/tx_engine.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/tx_fifo.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/tx_req_mux.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/common/tx_scheduler_rr.v
  /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/rtl/fpga.v
}
read_ip -quiet /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.srcs/sources_1/ip/cmac_usplus/cmac_usplus.xci
set_property is_enabled false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/cmac_usplus/synth/cmac_usplus.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/cmac_usplus/synth/cmac_usplus_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/cmac_usplus/synth/cmac_usplus_ooc.xdc]

add_files /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.srcs/sources_1/bd/cms/cms.bd
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_0/bd_fb99_build_info_cmc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_1/bd_fb99_build_info_host_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_2/bd_fb99_axi_gpio_timebase_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_2/bd_fb99_axi_gpio_timebase_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_2/bd_fb99_axi_gpio_timebase_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_3/bd_fb99_axi_gpio_cmc_mb_rst_n_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_3/bd_fb99_axi_gpio_cmc_mb_rst_n_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_3/bd_fb99_axi_gpio_cmc_mb_rst_n_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_4/bd_fb99_axi_gpio_hbm_temp_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_4/bd_fb99_axi_gpio_hbm_temp_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_4/bd_fb99_axi_gpio_hbm_temp_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_5/bd_fb99_axi_gpio_wdt_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_5/bd_fb99_axi_gpio_wdt_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_5/bd_fb99_axi_gpio_wdt_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_6/bd_fb99_axi_gpio_mb_intr_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_6/bd_fb99_axi_gpio_mb_intr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_6/bd_fb99_axi_gpio_mb_intr_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_7/bd_fb99_axi_gpio_mutex_cmc_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_7/bd_fb99_axi_gpio_mutex_cmc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_7/bd_fb99_axi_gpio_mutex_cmc_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_8/bd_fb99_axi_gpio_mutex_host_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_8/bd_fb99_axi_gpio_mutex_host_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_8/bd_fb99_axi_gpio_mutex_host_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_9/bd_fb99_axi_intc_cmc_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_9/bd_fb99_axi_intc_cmc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_9/bd_fb99_axi_intc_cmc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_10/bd_fb99_axi_intc_host_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_10/bd_fb99_axi_intc_host_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_10/bd_fb99_axi_intc_host_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_11/bd_fb99_axi_timebase_wdt_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_11/bd_fb99_axi_timebase_wdt_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_12/bd_fb99_axi_uartlite_satellite_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_12/bd_fb99_axi_uartlite_satellite_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_12/bd_fb99_axi_uartlite_satellite_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_13/bd_fb99_axi_uartlite_usb_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_13/bd_fb99_axi_uartlite_usb_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_13/bd_fb99_axi_uartlite_usb_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_15/bd_fb99_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_17/bd_fb99_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_18/bd_fb99_axi_bram_ctrl_firmware_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_19/bd_fb99_dlmb_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_20/bd_fb99_ilmb_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_21/bd_fb99_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_22/bd_fb99_lmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_23/bd_fb99_microblaze_cmc_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_23/bd_fb99_microblaze_cmc_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_23/bd_fb99_microblaze_cmc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_24/bd_fb99_microblaze_axi_vip_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_25/bd_fb99_reachout_axi_vip_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_26/bd_fb99_msp432_bsl_crc_gen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_27/bd_fb99_psreset_cmc_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_27/bd_fb99_psreset_cmc_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_27/bd_fb99_psreset_cmc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_28/bd_fb99_reg_map_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_29/bd_fb99_axi_bram_ctrl_regmap_cmc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_30/bd_fb99_axi_bram_ctrl_regmap_host_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_37/bd_fb99_freerun_counter_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_38/bd_fb99_axi_gpio_qsfp_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_38/bd_fb99_axi_gpio_qsfp_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_38/bd_fb99_axi_gpio_qsfp_0.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/bd_fb99_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/synth/cms_cms_subsystem_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/cms_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_0/ip/ip_23/data/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/fw/cms_xcu200_xcu250.elf]

read_ip -quiet /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.srcs/sources_1/ip/pcie4_uscale_plus_0/pcie4_uscale_plus_0.xci
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/pcie4_uscale_plus_0/ip_0/synth/pcie4_uscale_plus_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/pcie4_uscale_plus_0/ip_0/synth/pcie4_uscale_plus_0_gt.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/pcie4_uscale_plus_0/pcie4_uscale_plus_0_board.xdc]
set_property used_in_synthesis false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/pcie4_uscale_plus_0/source/ip_pcie4_uscale_plus_impl_x0y1.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/pcie4_uscale_plus_0/source/ip_pcie4_uscale_plus_impl_x0y1.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/pcie4_uscale_plus_0/synth/pcie4_uscale_plus_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/pcie4_uscale_plus_0/synth/pcie4_uscale_plus_0_late.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/pcie4_uscale_plus_0/source/ip_pcie4_uscale_plus_x0y1.xdc]

read_ip -quiet /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.srcs/sources_1/ip/cmac_gty_full/cmac_gty_full.xci
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/cmac_gty_full/synth/cmac_gty_full_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/cmac_gty_full/synth/cmac_gty_full.xdc]

read_ip -quiet /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.srcs/sources_1/ip/cmac_gty_channel/cmac_gty_channel.xci
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/cmac_gty_channel/synth/cmac_gty_channel_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/cmac_gty_channel/synth/cmac_gty_channel.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga.xdc
set_property used_in_implementation false [get_files /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/fpga.xdc]

read_xdc /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/placement.xdc
set_property used_in_implementation false [get_files /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/placement.xdc]

read_xdc /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/cfgmclk.xdc
set_property used_in_implementation false [get_files /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/cfgmclk.xdc]

read_xdc /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/boot.xdc
set_property used_in_implementation false [get_files /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/boot.xdc]

read_xdc -unmanaged /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axi/syn/vivado/axil_cdc.tcl
set_property used_in_implementation false [get_files /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axi/syn/vivado/axil_cdc.tcl]

read_xdc -unmanaged /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axis/syn/vivado/axis_async_fifo.tcl
set_property used_in_implementation false [get_files /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axis/syn/vivado/axis_async_fifo.tcl]

read_xdc -unmanaged /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axis/syn/vivado/sync_reset.tcl
set_property used_in_implementation false [get_files /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/axis/syn/vivado/sync_reset.tcl]

read_xdc -unmanaged /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/eth/syn/vivado/ptp_clock_cdc.tcl
set_property used_in_implementation false [get_files /home/ubuntu/git_repos/corundum/fpga/mqnic/AU250/fpga_100g/lib/eth/syn/vivado/ptp_clock_cdc.tcl]

read_xdc -unmanaged /home/ubuntu/git_repos/corundum/fpga/common/syn/vivado/mqnic_port.tcl
set_property used_in_implementation false [get_files /home/ubuntu/git_repos/corundum/fpga/common/syn/vivado/mqnic_port.tcl]

read_xdc -unmanaged /home/ubuntu/git_repos/corundum/fpga/common/syn/vivado/mqnic_ptp_clock.tcl
set_property used_in_implementation false [get_files /home/ubuntu/git_repos/corundum/fpga/common/syn/vivado/mqnic_ptp_clock.tcl]

read_xdc -unmanaged /home/ubuntu/git_repos/corundum/fpga/common/syn/vivado/mqnic_rb_clk_info.tcl
set_property used_in_implementation false [get_files /home/ubuntu/git_repos/corundum/fpga/common/syn/vivado/mqnic_rb_clk_info.tcl]

read_xdc -unmanaged /home/ubuntu/git_repos/corundum/fpga/common/syn/vivado/rb_drp.tcl
set_property used_in_implementation false [get_files /home/ubuntu/git_repos/corundum/fpga/common/syn/vivado/rb_drp.tcl]

read_xdc -unmanaged /home/ubuntu/git_repos/corundum/fpga/common/syn/vivado/cmac_gty_wrapper.tcl
set_property used_in_implementation false [get_files /home/ubuntu/git_repos/corundum/fpga/common/syn/vivado/cmac_gty_wrapper.tcl]

read_xdc -unmanaged /home/ubuntu/git_repos/corundum/fpga/common/syn/vivado/cmac_gty_ch_wrapper.tcl
set_property used_in_implementation false [get_files /home/ubuntu/git_repos/corundum/fpga/common/syn/vivado/cmac_gty_ch_wrapper.tcl]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top fpga -part xcu250-figd2104-2-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fpga.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fpga_utilization_synth.rpt -pb fpga_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
