# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.srcs/sources_1/ip/pcie4_uscale_plus_0/pcie4_uscale_plus_0.xci
# IP: The module: 'pcie4_uscale_plus_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/pcie4_uscale_plus_0/ip_0/pcie4_uscale_plus_0_gt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pcie4_uscale_plus_0_gt || ORIG_REF_NAME==pcie4_uscale_plus_0_gt} -quiet] -quiet

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/pcie4_uscale_plus_0/ip_0/synth/pcie4_uscale_plus_0_gt_ooc.xdc

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/pcie4_uscale_plus_0/ip_0/synth/pcie4_uscale_plus_0_gt.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie4_uscale_plus_0_gt || ORIG_REF_NAME==pcie4_uscale_plus_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/pcie4_uscale_plus_0/pcie4_uscale_plus_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie4_uscale_plus_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/pcie4_uscale_plus_0/source/ip_pcie4_uscale_plus_impl_x0y1.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie4_uscale_plus_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/pcie4_uscale_plus_0/synth/pcie4_uscale_plus_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie4_uscale_plus_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/pcie4_uscale_plus_0/synth/pcie4_uscale_plus_0_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie4_uscale_plus_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/pcie4_uscale_plus_0/source/ip_pcie4_uscale_plus_x0y1.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie4_uscale_plus_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.srcs/sources_1/ip/pcie4_uscale_plus_0/pcie4_uscale_plus_0.xci
# IP: The module: 'pcie4_uscale_plus_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/pcie4_uscale_plus_0/ip_0/pcie4_uscale_plus_0_gt.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pcie4_uscale_plus_0_gt || ORIG_REF_NAME==pcie4_uscale_plus_0_gt} -quiet] -quiet

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/pcie4_uscale_plus_0/ip_0/synth/pcie4_uscale_plus_0_gt_ooc.xdc

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/pcie4_uscale_plus_0/ip_0/synth/pcie4_uscale_plus_0_gt.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie4_uscale_plus_0_gt || ORIG_REF_NAME==pcie4_uscale_plus_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/pcie4_uscale_plus_0/pcie4_uscale_plus_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie4_uscale_plus_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/pcie4_uscale_plus_0/source/ip_pcie4_uscale_plus_impl_x0y1.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie4_uscale_plus_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/pcie4_uscale_plus_0/synth/pcie4_uscale_plus_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie4_uscale_plus_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/pcie4_uscale_plus_0/synth/pcie4_uscale_plus_0_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie4_uscale_plus_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/pcie4_uscale_plus_0/source/ip_pcie4_uscale_plus_x0y1.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie4_uscale_plus_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
