# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_16/bd_43c9_axi_gpio_mb_intr_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_43c9_axi_gpio_mb_intr_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_16/bd_43c9_axi_gpio_mb_intr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_43c9_axi_gpio_mb_intr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_16/bd_43c9_axi_gpio_mb_intr_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_43c9_axi_gpio_mb_intr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_16/bd_43c9_axi_gpio_mb_intr_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_43c9_axi_gpio_mb_intr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_16/bd_43c9_axi_gpio_mb_intr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_43c9_axi_gpio_mb_intr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/bd/cms/ip/cms_cms_subsystem_0_0/bd_1/ip/ip_16/bd_43c9_axi_gpio_mb_intr_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_43c9_axi_gpio_mb_intr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
