# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.srcs/sources_1/ip/cmac_gty_channel/cmac_gty_channel.xci
# IP: The module: 'cmac_gty_channel' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/cmac_gty_channel/synth/cmac_gty_channel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmac_gty_channel'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/cmac_gty_channel/synth/cmac_gty_channel.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmac_gty_channel'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.srcs/sources_1/ip/cmac_gty_channel/cmac_gty_channel.xci
# IP: The module: 'cmac_gty_channel' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/cmac_gty_channel/synth/cmac_gty_channel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmac_gty_channel'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/caogang/corundum/fpga/mqnic/AU250/fpga_100g/fpga/fpga.gen/sources_1/ip/cmac_gty_channel/synth/cmac_gty_channel.xdc
# XDC: The top module name and the constraint reference have the same name: 'cmac_gty_channel'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
